DROP DATABASE IF EXISTS d50pe1mdawgc8ok4;
CREATE DATABASE d50pe1mdawgc8ok4;
USE d50pe1mdawgc8ok4;

CREATE TABLE burgers(
    id INTEGER NOT NULL AUTO_INCREMENT, 
    burger_name VARCHAR(45) NULL,
    devoured BOOLEAN DEFAULT false,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
